#ifndef _COLOR_H
#define  _COLOR_H
namespace JFC {
#define FCOLOR_BLACK			0//前景黑色
#define FCOLOR_BLUE				FOREGROUND_BLUE// 前景蓝色
#define FCOLOR_GREEN			FOREGROUND_GREEN// 前景绿色
#define FCOLOR_CYAN				FOREGROUND_BLUE | FOREGROUND_GREEN // 前景青色
#define FCOLOR_RED				FOREGROUND_RED // 前景红色
#define FCOLOR_MAGENTA			FOREGROUND_RED | FOREGROUND_BLUE // 前景洋红
#define FCOLOR_BLOWN			FOREGROUND_RED | FOREGROUND_GREEN // 前景棕色
#define FCOLOR_GRAY				FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE // 淡灰
#define FCOLOR_DARKGRAY			FCOLOR_BLACK + FOREGROUND_INTENSITY // 前景深灰
#define FCOLOR_LIGHTBLUE		FCOLOR_BLUE + FOREGROUND_INTENSITY // 前景淡蓝
#define FCOLOR_LIGHTGREEN		FCOLOR_GREEN + FOREGROUND_INTENSITY // 前景淡绿
#define FCOLOR_LIGHTCYAN		FCOLOR_CYAN + FOREGROUND_INTENSITY // 前景淡青
#define FCOLOR_LIGHTRED			FCOLOR_RED + FOREGROUND_INTENSITY // 前景淡红
#define FCOLOR_LIGHTMAGENTA		FCOLOR_MAGENTA + FOREGROUND_INTENSITY // 前景淡洋红
#define FCOLOR_YELLO			FCOLOR_BLOWN + FOREGROUND_INTENSITY // 前景黄色
#define FCOLOR_WHITE			FCOLOR_GRAY + FOREGROUND_INTENSITY // 前景白色

#define BCOLOR_BLACK			0 // 背景黑色
#define BCOLOR_BLUE				BACKGROUND_BLUE// 背景蓝色
#define BCOLOR_GREEN			BACKGROUND_GREEN // 背景绿色
#define BCOLOR_CYAN				BACKGROUND_BLUE | BACKGROUND_GREEN // 背景青色
#define BCOLOR_RED				BACKGROUND_RED // 背景红色
#define BCOLOR_MAGENTA			BACKGROUND_RED | BACKGROUND_BLUE // 背景洋红
#define BCOLOR_BLOWN			BACKGROUND_RED | BACKGROUND_GREEN // 背景棕色
#define BCOLOR_GRAY				BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE// 淡灰
#define BCOLOR_DARKGRAY			BCOLOR_BLACK + BACKGROUND_INTENSITY // 背景深灰
#define BCOLOR_LIGHTBLUE		BCOLOR_BLUE + BACKGROUND_INTENSITY // 背景淡蓝
#define BCOLOR_LIGHTGREEN		BCOLOR_GREEN + BACKGROUND_INTENSITY // 背景淡绿
#define BCOLOR_LIGHTCYAN		BCOLOR_CYAN + BACKGROUND_INTENSITY  // 背景淡青
#define BCOLOR_LIGHTRED			BCOLOR_RED + BACKGROUND_INTENSITY  // 背景淡红
#define BCOLOR_LIGHTMAGENTA		BCOLOR_MAGENTA + BACKGROUND_INTENSITY // 背景淡洋红
#define BCOLOR_YELLO			BCOLOR_BLOWN + BACKGROUND_INTENSITY  // 背景黄色
#define BCOLOR_WHITE			BCOLOR_GRAY + BACKGROUND_INTENSITY // 背景白色

}

#endif // !_COLOR_H

